package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"unicode"
)

type typeDef struct {
	name string
	spec *ast.TypeSpec
}

type typeOutput struct {
	text    string
	usesMap bool
}

func main() {
	flag.Parse()

	goFile := strings.TrimSpace(os.Getenv("GOFILE"))
	if goFile == "" {
		fmt.Fprintln(os.Stderr, "amgen-go: GOFILE is not set; run via go generate")
		os.Exit(1)
	}
	if !strings.HasSuffix(goFile, ".go") {
		fmt.Fprintf(os.Stderr, "amgen-go: GOFILE must be a .go file, got %q\n", goFile)
		os.Exit(1)
	}
	inputValue := goFile
	outValue := strings.TrimSuffix(goFile, ".go") + ".rs"
	if err := run(inputValue, outValue); err != nil {
		fmt.Fprintf(os.Stderr, "amgen-go: %v\n", err)
		os.Exit(1)
	}
}

func run(input, out string) error {
	inputAbs, err := filepath.Abs(input)
	if err != nil {
		return err
	}
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, inputAbs, nil, parser.ParseComments)
	if err != nil {
		return err
	}

	typeDefs := collectTypeDefs(file)
	if len(typeDefs) == 0 {
		return fmt.Errorf("no types found in %s", input)
	}
	if isRustKeyword(file.Name.Name) {
		return fmt.Errorf("package name %q is a Rust keyword", file.Name.Name)
	}
	if !isRustIdent(file.Name.Name) {
		return fmt.Errorf("package name %q is not a valid Rust module name", file.Name.Name)
	}

	structNames := map[string]bool{}
	for _, def := range typeDefs {
		if _, ok := def.spec.Type.(*ast.StructType); ok {
			structNames[def.name] = true
		}
	}

	var outputs []typeOutput
	usesMap := false
	for _, def := range typeDefs {
		outDef, err := renderType(def, structNames)
		if err != nil {
			return fmt.Errorf("%s: %w", def.name, err)
		}
		outputs = append(outputs, outDef)
		if outDef.usesMap {
			usesMap = true
		}
	}

	message, err := renderRust(file.Name.Name, outputs, usesMap)
	if err != nil {
		return err
	}

	outPath := filepath.Clean(out)
	outFile := outPath
	if !strings.HasSuffix(outPath, ".rs") {
		outFile = filepath.Join(outPath, "message.rs")
	}
	outAbs, err := filepath.Abs(outFile)
	if err != nil {
		return err
	}
	repoRoot, err := findGoModRoot(filepath.Dir(inputAbs))
	if err != nil {
		return err
	}
	rel, err := filepath.Rel(repoRoot, outAbs)
	if err != nil {
		return err
	}
	if rel == ".." || strings.HasPrefix(rel, ".."+string(os.PathSeparator)) {
		return fmt.Errorf("output must be inside repo root %s", repoRoot)
	}
	needCargo, err := checkRootCargo(repoRoot, file.Name.Name, "lib.rs")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(outAbs), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(outAbs, message, 0o644); err != nil {
		return err
	}

	// Derive the api module path: e.g. "api/hello/message.rs" → dir "api/hello", mod name "hello"
	relSlash := filepath.ToSlash(rel)
	relDir := filepath.ToSlash(filepath.Dir(rel))
	modName := filepath.Base(relDir)
	if !isRustIdent(modName) {
		return fmt.Errorf("directory name %q is not a valid Rust module name", modName)
	}
	libRS := renderLibRS(relSlash, relDir, modName)
	libPath := filepath.Join(repoRoot, "lib.rs")
	if err := os.WriteFile(libPath, []byte(libRS), 0o644); err != nil {
		return err
	}

	if needCargo {
		return writeRootCargo(repoRoot, file.Name.Name, "lib.rs")
	}
	return nil
}

func renderRust(moduleName string, outputs []typeOutput, usesMap bool) ([]byte, error) {
	var buf bytes.Buffer
	writeLine(&buf, 0, "// Code generated by amgen-go; DO NOT EDIT.")
	writeLine(&buf, 0, "use adaptivemsg as am;")
	if usesMap {
		writeLine(&buf, 0, "use std::collections::BTreeMap;")
	}
	writeLine(&buf, 0, "")
	for i, outDef := range outputs {
		if i != 0 {
			writeLine(&buf, 0, "")
		}
		buf.WriteString(outDef.text)
	}
	return buf.Bytes(), nil
}

func writeRootCargo(repoRoot, crateName, libPath string) error {
	if !isValidCrateName(crateName) {
		return fmt.Errorf("package name %q is not a valid crate name", crateName)
	}
	cargo := renderRootCargo(crateName, libPath)
	cargoPath := filepath.Join(repoRoot, "Cargo.toml")
	return os.WriteFile(cargoPath, []byte(cargo), 0o644)
}

func checkRootCargo(repoRoot, crateName, libPath string) (bool, error) {
	cargoPath := filepath.Join(repoRoot, "Cargo.toml")
	if _, err := os.Stat(cargoPath); err == nil {
		// Cargo.toml already exists; leave it as-is.
		return false, nil
	} else if !os.IsNotExist(err) {
		return false, err
	}
	return true, nil
}

func findGoModRoot(start string) (string, error) {
	dir := start
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		} else if !os.IsNotExist(err) {
			return "", err
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return "", fmt.Errorf("go.mod not found for %s", start)
}

func renderRootCargo(crateName, libPath string) string {
	var buf bytes.Buffer
	writeLine(&buf, 0, "[package]")
	writeLine(&buf, 0, fmt.Sprintf("name = %q", crateName))
	writeLine(&buf, 0, "version = \"0.0.0\"")
	writeLine(&buf, 0, "edition = \"2021\"")
	writeLine(&buf, 0, "")
	writeLine(&buf, 0, "[lib]")
	writeLine(&buf, 0, fmt.Sprintf("path = %q", libPath))
	writeLine(&buf, 0, "")
	writeLine(&buf, 0, "[dependencies]")
	writeLine(&buf, 0, "serde = { version = \"1.0\", features = [\"derive\"] }")
	writeLine(&buf, 0, "# adaptivemsg = { path = \"...\" }")
	writeLine(&buf, 0, "")
	writeLine(&buf, 0, "# TODO: set a real version and adaptivemsg dependency before publishing.")
	return buf.String()
}

// renderLibRS generates a lib.rs that preserves the api directory structure.
// For "api/hello/message.rs" it produces:
//
//	pub mod api {
//	    #[path = "hello/message.rs"]
//	    pub mod hello;
//	}
//
// Rust resolves #[path] inside an inline module relative to that module's
// implicit directory. So inside `pub mod api { ... }`, the base directory
// is `api/`, and we only need the path relative to it.
func renderLibRS(rsPath, rsDir, modName string) string {
	parts := strings.Split(rsDir, "/")
	var buf bytes.Buffer
	writeLine(&buf, 0, "// Code generated by amgen-go; DO NOT EDIT.")

	// Open nested pub mod for all parts except the leaf
	for i, part := range parts[:len(parts)-1] {
		writeLine(&buf, i, fmt.Sprintf("pub mod %s {", part))
	}

	// Inside the innermost wrapper module, #[path] is relative to
	// the implicit directory of all enclosing inline modules.
	// e.g. inside `pub mod api { ... }`, base dir is "api/",
	// so to reach "api/hello/message.rs" we need "hello/message.rs".
	// For deeper nesting (api/foo/bar/), strip leading segments.
	innerRelPath := strings.Join(append(parts[1:], filepath.Base(rsPath)), "/")

	depth := len(parts) - 1
	writeLine(&buf, depth, fmt.Sprintf("#[path = %q]", innerRelPath))
	writeLine(&buf, depth, fmt.Sprintf("pub mod %s;", modName))

	// Close nested modules
	for i := len(parts) - 2; i >= 0; i-- {
		writeLine(&buf, i, "}")
	}
	return buf.String()
}

func collectTypeDefs(file *ast.File) []typeDef {
	var defs []typeDef
	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			defs = append(defs, typeDef{
				name: typeSpec.Name.Name,
				spec: typeSpec,
			})
		}
	}
	return defs
}

func renderType(def typeDef, structNames map[string]bool) (typeOutput, error) {
	if isRustKeyword(def.name) {
		return typeOutput{}, fmt.Errorf("type name %q is a Rust keyword", def.name)
	}
	if !isRustIdent(def.name) {
		return typeOutput{}, fmt.Errorf("type name %q is not a valid Rust identifier", def.name)
	}
	if structType, ok := def.spec.Type.(*ast.StructType); ok {
		text, usesMap, err := renderStruct(def.name, structType, structNames)
		if err != nil {
			return typeOutput{}, err
		}
		return typeOutput{text: text, usesMap: usesMap}, nil
	}
	rustType, usesMap, err := rustType(def.spec.Type, structNames, false)
	if err != nil {
		return typeOutput{}, err
	}
	return typeOutput{
		text:    fmt.Sprintf("pub type %s = %s;\n", def.name, rustType),
		usesMap: usesMap,
	}, nil
}

func renderStruct(name string, st *ast.StructType, structNames map[string]bool) (string, bool, error) {
	var buf bytes.Buffer
	writeLine(&buf, 0, "#[am::message]")
	writeLine(&buf, 0, fmt.Sprintf("pub struct %s {", name))

	usesMap := false
	seenFields := map[string]bool{}
	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			return "", false, fmt.Errorf("embedded fields are not supported")
		}
		if len(field.Names) != 1 {
			return "", false, fmt.Errorf("struct fields must be declared one per line")
		}
		nameIdent := field.Names[0]
		if !ast.IsExported(nameIdent.Name) {
			continue
		}
		tagName, omit, hasTag, err := parseAMTag(field.Tag)
		if err != nil {
			return "", false, fmt.Errorf("%s.%s: %w", name, nameIdent.Name, err)
		}
		if !hasTag {
			return "", false, fmt.Errorf("missing am tag on %s.%s (add am:%q or am:\"-\")", name, nameIdent.Name, toSnake(nameIdent.Name))
		}
		if omit {
			continue
		}

		rustField := toSnake(nameIdent.Name)
		if rustField == "" {
			return "", false, fmt.Errorf("invalid field name %q", nameIdent.Name)
		}
		if !isRustIdent(rustField) {
			return "", false, fmt.Errorf("field name %q is not a valid Rust identifier", rustField)
		}
		if isRustKeyword(rustField) {
			rustField = "r#" + rustField
		}
		if seenFields[rustField] {
			return "", false, fmt.Errorf("duplicate Rust field name %q", rustField)
		}
		seenFields[rustField] = true

		rustTy, fieldUsesMap, err := rustType(field.Type, structNames, false)
		if err != nil {
			return "", false, err
		}
		if fieldUsesMap {
			usesMap = true
		}

		serdeName := strings.TrimPrefix(rustField, "r#")
		if tagName != serdeName {
			writeLine(&buf, 1, fmt.Sprintf("#[serde(rename = %q)]", tagName))
		}
		writeLine(&buf, 1, fmt.Sprintf("pub %s: %s,", rustField, rustTy))
	}

	writeLine(&buf, 0, "}")
	return buf.String(), usesMap, nil
}

func parseAMTag(tag *ast.BasicLit) (string, bool, bool, error) {
	if tag == nil {
		return "", false, false, nil
	}
	raw := tag.Value
	unquoted, err := strconv.Unquote(raw)
	if err != nil {
		unquoted = strings.Trim(raw, "`\"")
	}
	amTag := reflect.StructTag(unquoted).Get("am")
	if amTag == "" {
		return "", false, false, nil
	}
	name, _, _ := strings.Cut(amTag, ",")
	if name == "" {
		return "", false, true, fmt.Errorf("am tag must include a name or '-'")
	}
	if name == "-" {
		return "", true, true, nil
	}
	return name, false, true, nil
}

func rustType(expr ast.Expr, structNames map[string]bool, mapKey bool) (string, bool, error) {
	switch t := expr.(type) {
	case *ast.Ident:
		return rustIdentType(t.Name, structNames, mapKey)
	case *ast.StarExpr:
		if mapKey {
			return "", false, fmt.Errorf("map key cannot be a pointer")
		}
		inner, usesMap, err := rustType(t.X, structNames, false)
		if err != nil {
			return "", false, err
		}
		return fmt.Sprintf("Option<%s>", inner), usesMap, nil
	case *ast.ArrayType:
		if mapKey {
			return "", false, fmt.Errorf("map key cannot be a slice or array")
		}
		inner, usesMap, err := rustType(t.Elt, structNames, false)
		if err != nil {
			return "", false, err
		}
		if t.Len == nil {
			return fmt.Sprintf("Vec<%s>", inner), usesMap, nil
		}
		lenLit, ok := t.Len.(*ast.BasicLit)
		if !ok || lenLit.Kind != token.INT {
			return "", false, fmt.Errorf("array length must be an int literal")
		}
		return fmt.Sprintf("[%s; %s]", inner, lenLit.Value), usesMap, nil
	case *ast.MapType:
		if mapKey {
			return "", false, fmt.Errorf("map key cannot be a map")
		}
		key, _, err := rustType(t.Key, structNames, true)
		if err != nil {
			return "", false, err
		}
		val, _, err := rustType(t.Value, structNames, false)
		if err != nil {
			return "", false, err
		}
		return fmt.Sprintf("BTreeMap<%s, %s>", key, val), true, nil
	case *ast.SelectorExpr:
		return "", false, fmt.Errorf("qualified types are not supported")
	case *ast.StructType:
		return "", false, fmt.Errorf("anonymous struct types are not supported")
	case *ast.InterfaceType:
		return "", false, fmt.Errorf("interface types are not supported")
	case *ast.FuncType:
		return "", false, fmt.Errorf("func types are not supported")
	case *ast.ChanType:
		return "", false, fmt.Errorf("chan types are not supported")
	case *ast.ParenExpr:
		return rustType(t.X, structNames, mapKey)
	default:
		return "", false, fmt.Errorf("unsupported type")
	}
}

func rustIdentType(name string, structNames map[string]bool, mapKey bool) (string, bool, error) {
	switch name {
	case "bool":
		return "bool", false, nil
	case "string":
		return "String", false, nil
	case "int":
		return "i64", false, nil
	case "int8":
		return "i8", false, nil
	case "int16":
		return "i16", false, nil
	case "int32":
		return "i32", false, nil
	case "int64":
		return "i64", false, nil
	case "uint":
		return "u64", false, nil
	case "uint8":
		return "u8", false, nil
	case "uint16":
		return "u16", false, nil
	case "uint32":
		return "u32", false, nil
	case "uint64":
		return "u64", false, nil
	case "uintptr":
		return "u64", false, nil
	case "byte":
		return "u8", false, nil
	case "rune":
		return "i32", false, nil
	case "float32":
		if mapKey {
			return "", false, fmt.Errorf("map key cannot be float32")
		}
		return "f32", false, nil
	case "float64":
		if mapKey {
			return "", false, fmt.Errorf("map key cannot be float64")
		}
		return "f64", false, nil
	case "complex64", "complex128":
		return "", false, fmt.Errorf("complex types are not supported")
	default:
		if mapKey && structNames[name] {
			return "", false, fmt.Errorf("map key cannot be struct type %s", name)
		}
		return name, false, nil
	}
}

func toSnake(input string) string {
	if input == "" {
		return ""
	}
	var out strings.Builder
	runes := []rune(input)
	for i, r := range runes {
		if r == '_' {
			out.WriteRune(r)
			continue
		}
		if unicode.IsUpper(r) {
			if i > 0 {
				prev := runes[i-1]
				nextLower := i+1 < len(runes) && unicode.IsLower(runes[i+1])
				if unicode.IsLower(prev) || unicode.IsDigit(prev) || (unicode.IsUpper(prev) && nextLower) {
					out.WriteRune('_')
				}
			}
			out.WriteRune(unicode.ToLower(r))
			continue
		}
		out.WriteRune(r)
	}
	return out.String()
}

func isRustIdent(name string) bool {
	if name == "" {
		return false
	}
	for i, r := range name {
		if r > unicode.MaxASCII {
			return false
		}
		if i == 0 {
			if r != '_' && !unicode.IsLetter(r) {
				return false
			}
			continue
		}
		if r != '_' && !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			return false
		}
	}
	return true
}

func isValidCrateName(name string) bool {
	if name == "" {
		return false
	}
	for i, r := range name {
		if r > unicode.MaxASCII {
			return false
		}
		if i == 0 && unicode.IsDigit(r) {
			return false
		}
		if r == '-' || r == '_' || unicode.IsLetter(r) || unicode.IsDigit(r) {
			continue
		}
		return false
	}
	return true
}

func isRustKeyword(name string) bool {
	switch name {
	case "as", "break", "const", "continue", "crate", "else", "enum", "extern",
		"false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod",
		"move", "mut", "pub", "ref", "return", "self", "Self", "static", "struct",
		"super", "trait", "true", "type", "unsafe", "use", "where", "while",
		"async", "await", "dyn", "abstract", "become", "box", "do", "final",
		"macro", "override", "priv", "typeof", "unsized", "virtual", "yield", "try":
		return true
	default:
		return false
	}
}

func writeLine(buf *bytes.Buffer, indent int, line string) {
	for i := 0; i < indent; i++ {
		buf.WriteString("    ")
	}
	buf.WriteString(line)
	buf.WriteString("\n")
}

func indentLines(input string, indent int) string {
	if indent == 0 || input == "" {
		return input
	}
	prefix := strings.Repeat("    ", indent)
	lines := strings.Split(input, "\n")
	for i, line := range lines {
		if line == "" && i == len(lines)-1 {
			continue
		}
		lines[i] = prefix + line
	}
	return strings.Join(lines, "\n")
}
